global:
  scrape_interval: 10s #Scrape interval to every 15 seconds.
  evaluation_interval: 10s #Evaluate rules every 15 seconds.
  
scrape_configs:
    # metrics_path defaults to '/metrics'
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "cinema-api"
    static_configs:
      - targets: ["app:5000"]